#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parents[1]

    parser = argparse.ArgumentParser(
        description="Extract the leading BIN value from the MQN column.",
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=repo_root / "datasets" / "ZINC_ChEMBL34_hi_conf_1M_MQN.csv",
        help="Input CSV generated by 1_add_MQN2file.sh.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=repo_root / "datasets" / "ZINC_ChEMBL34_hi_conf_1M_MQN_BIN.csv",
        help="Output CSV with BIN extracted from the MQN column.",
    )
    return parser.parse_args()


def extract_bin(df: pd.DataFrame) -> pd.DataFrame:
    if "MQN" not in df.columns:
        raise ValueError("Input CSV must contain an 'MQN' column.")

    result = df.copy()
    result["BIN"] = result["MQN"].str.extract(r"\[(\d+)", expand=False).astype("Int64")
    result["MQN"] = result["MQN"].str.replace(r"^\[\d+,\s*", "[", regex=True)
    return result


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)

    df = pd.read_csv(input_path)
    result = extract_bin(df)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(output_path, index=False)

    print(f"Read {len(df)} rows from {input_path}")
    print(f"Wrote {len(result)} rows to {output_path}")


if __name__ == "__main__":
    main()
