#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parents[1]

    parser = argparse.ArgumentParser(
        description="Remove query drugs from the base MQN CSV and append normalized query rows.",
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=repo_root / "datasets" / "ZINC_ChEMBL34_hi_conf_1M_MQN_BIN.csv",
        help="Input CSV generated by 2_extract_BIN.py.",
    )
    parser.add_argument(
        "--query",
        type=Path,
        default=repo_root / "datasets" / "145-ChEMBL34_top-sellers_23_FINAL.csv",
        help="Query CSV containing the curated drug set.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=repo_root / "datasets" / "ZINC_ChEMBL34_hi_conf_1M_145-drugs_MQN_BIN.csv",
        help="Output CSV for downstream MHFP generation.",
    )
    return parser.parse_args()


def normalize_query(df_query_raw: pd.DataFrame) -> pd.DataFrame:
    required = {"SMILES", "ID", "SUM_BIN", "MQN"}
    missing = required - set(df_query_raw.columns)
    if missing:
        raise ValueError(f"Query CSV is missing required columns: {sorted(missing)}")

    return pd.DataFrame(
        {
            "SMILES": df_query_raw["SMILES"],
            "ID": df_query_raw["ID"],
            "MQN": df_query_raw["MQN"],
            "BIN": df_query_raw["SUM_BIN"],
        }
    )


def main() -> None:
    args = parse_args()

    df_input = pd.read_csv(args.input)
    df_query_raw = pd.read_csv(args.query)
    df_query = normalize_query(df_query_raw)

    mask = df_input["ID"].isin(df_query["ID"])
    discarded = int(mask.sum())
    df_input_filtered = df_input.loc[~mask].copy()

    df_concat = pd.concat([df_input_filtered, df_query], ignore_index=True)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    df_concat.to_csv(args.output, index=False)

    print(f"Read {len(df_input)} base rows from {args.input}")
    print(f"Read {len(df_query)} query rows from {args.query}")
    print(f"Removed {discarded} overlapping rows from the base dataset")
    print(f"Wrote {len(df_concat)} rows to {args.output}")


if __name__ == "__main__":
    main()
